### ISSUE TITLE
Python 2 but NOT python 3?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#21]
./make.py  brought me the following ERROR message:

```
......./openmv/openmv-ide$ ./make.py
Traceback (most recent call last):
  File "./make.py", line 253, in <module>
    make()
  File "./make.py", line 228, in make
    " && make installer INSTALL_ROOT="+installdir + " IFW_PATH="+ifdir):
TypeError: must be str, not NoneType
```

My python:
```
$ python --version
Python 3.6.5
```

Cheers
Pei

**Comment by kwagyeman** [comment]
Make sure installdir and ifdir are defined.  Check how those variables get their values and figure out why they are None versus being a string.
