### ISSUE TITLE
Is current openmv-ide still ONLY compatible with Python 2?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#26]
Is current openmv-ide still ONLY compatible with Python 2??

I'm now building with Python 3.6.5, but got the following errors...

```
fixing rpaths...
`....../openmv-ide/build/install/README.txt' probably isn't an ELF file.
elf_open: Exec format error
Traceback (most recent call last):
  File "....../openmv-ide/qt-creator/scripts/deployqt.py", line 339, in <module>
    main()
  File "....../openmv-ide/qt-creator/scripts/deployqt.py", line 328, in main
    common.fix_rpaths(install_dir, os.path.join(qt_deploy_prefix, 'lib'), qt_install_info, chrpath_bin)
  File "....../openmv-ide/qt-creator/scripts/common.py", line 187, in fix_rpaths
    if (is_unix_executable(filepath) or is_unix_library(filepath)):
  File "....../openmv-ide/qt-creator/scripts/common.py", line 178, in is_unix_executable
    return (f.read(2) != "#!")
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 25: invalid start byte
Makefile:581: recipe for target 'deployqt' failed
make: *** [deployqt] Error 1
Make Failed...
[2]+  Done     
```

**Comment by kwagyeman** [comment]
I'm not fixing this... Building the IDE is something to do for very advanced users and you've been posting issues about having trouble building it and posting stack traces that clearly shows the problem. If you want to sumbit a PR that fixes the issue go ahead and I'll merge it. But, it's a won't fix for me otherwise.
